# -*- coding: utf-8 -*-
"""maintainance-monitoringipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/AdeebaRafi/b177fbf3ccc324f8db06adb33fca3079/maintainance-monitoringipynb.ipynb
"""

# Install necessary libraries (if not already installed)
# Uncomment this line if you're missing the Gradio library
# !pip install gradio
!pip install gradio
import datetime
import gradio as gr

# Function to predict maintenance details for IT infrastructure
def predict_server_maintenance(last_service_date, cpu_load, storage_utilization, temperature):
    try:
        # Parse the last service date
        last_service = datetime.datetime.strptime(last_service_date, "%Y-%m-%d")

        # Calculate maintenance interval based on metrics
        if cpu_load > 80 or storage_utilization > 90 or temperature > 75:
            maintenance_interval = 30  # High risk: 30 days
            risk_level = "High"
        elif cpu_load > 60 or storage_utilization > 70 or temperature > 60:
            maintenance_interval = 60  # Medium risk: 60 days
            risk_level = "Medium"
        else:
            maintenance_interval = 90  # Low risk: 90 days
            risk_level = "Low"

        # Calculate the next service date
        next_service_date = last_service + datetime.timedelta(days=maintenance_interval)

        # Return the prediction results
        return {
            "Next Service Date": next_service_date.strftime("%Y-%m-%d"),
            "Risk Level": risk_level
        }
    except Exception as e:
        return {"Error": str(e)}

# Custom CSS for styling the Gradio interface
custom_css = """
body {
    background: grey;
    color: #1b5e20;
    font-family: Arial, sans-serif;
}

h1, h2, h3, h4, h5, h6 {
    color: blue;
}

.gradio-container {
    border-radius: 12px;
    box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.2);
    padding: 20px;
}

label {
    color: blue;
    font-weight: bold;
}

.gr-button {
    background-color: #01579b;
    color: white;
    border: none;
    border-radius: 8px;
    font-size: 16px;
    padding: 8px 16px;
}

.gr-button:hover {
    background-color: #0277bd;
}
"""

# Gradio interface definition
interface = gr.Interface(
    fn=predict_server_maintenance,
    inputs=[
        gr.Textbox(label="Last Service Date (YYYY-MM-DD)", placeholder="e.g., 2025-01-01"),
        gr.Slider(label="CPU Load (%)", minimum=0, maximum=100, step=1, value=50),
        gr.Slider(label="Storage Utilization (%)", minimum=0, maximum=100, step=1, value=50),
        gr.Slider(label="Temperature (°C)", minimum=0, maximum=100, step=1, value=25)
    ],
    outputs=gr.JSON(label="Maintenance Prediction"),
    title="IT Infrastructure Maintenance Tool",
    description="Predict the next maintenance date and risk level for servers and data center components based on CPU load, storage utilization, and temperature.",
    theme="compact",
    css=custom_css
)

# Launch the Gradio interface
interface.launch()